import Header from "@/components/Header";
import ReduxProvider from "@/components/ReduxProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header></Header>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
